export const data = [
    {
        id: 1,
        title: "The Shawshank Redemption",
        poster: "shawshank",
        banner: "shawshankbanner",
        bannerHeight: "400px",
        director: "Frank Darabont",
        description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
        releaseYear: 1994,
        maturity: "R",
        genre: "Drama",
        length: "2h22m",
        rating: 9.3,
    },
    {
        id: 2,
        title: "The Godfather",
        poster: "god",
        banner: "godbanner",
        bannerHeight: "400px",
        director: "Francis Ford Coppola",
        description: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        releaseYear: 1972,
        maturity: "R",
        genre: "Drama",
        length: "2h55m",
        rating: 9.2,
    },
    {
        id: 3,
        title: "The Godfather Part II",
        poster: "god2",
        banner: "god2banner",
        bannerHeight: "400px",
        director: "Francis Ford Coppola",
        description: "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
        releaseYear: 1974,
        maturity: "R",
        genre: "Drama",
        length: "3h22m",
        rating: 9.0,
    },
    {
        id: 4,
        title: "Schindler's List",
        poster: "list",
        banner: "listbanner",
        bannerHeight: "400px",
        director: "Steven Spielberg",
        description: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
        releaseYear: 1993,
        maturity: "R",
        genre: "History",
        length: "3h15m",
        rating: 8.9,
    },
    {
        id: 5,
        title: "Pulp Fiction",
        poster: "pulp",
        banner: "pulpbanner",
        bannerHeight: "400px",
        director: "Quentin Tarantino",
        description: "A burger-loving hit man, his philosophical partner, a drug-addled gangster’s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        releaseYear: 1994,
        maturity: "R",
        genre: "Drama",
        length: "2h34m",
        rating: 8.9,
    },
    {
        id: 6,
        title: "Forrest Gump",
        poster: "forrest",
        banner: "forrestbanner",
        bannerHeight: "400px",
        director: "Robert Zemeckis",
        description: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
        releaseYear: 1994,
        maturity: "PG-13",
        genre: "Drama",
        length: "2h22m",
        rating: 8.8,
    },
    {
        id: 7,
        title: "Fight Club",
        poster: "fight",
        banner: "fightbanner",
        bannerHeight: "400px",
        director: "David Fincher",
        description: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground “fight clubs” forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
        releaseYear: 1999,
        maturity: "R",
        genre: "Drama",
        length: "2h19m",
        rating: 8.8,
    },
    {
        id: 8,
        title: "Inception",
        poster: "inception",
        banner: "inceptionbanner",
        bannerHeight: "420px",
        director: "Christopher Nolan",
        description: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: “inception”, the implantation of another person’s idea into a target’s subconscious.",
        releaseYear: 2010,
        maturity: "PG-13",
        genre: "Sci-Fi",
        length: "2h28m",
        rating: 8.8,
    },
    {
        id: 9,
        title: "The Dark Knight",
        poster: "darkknight",
        banner: "darkknightbanner",
        bannerHeight: "470px",
        director: "Christopher Nolan",
        description: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        releaseYear: 2008,
        maturity: "PG-13",
        genre: "Action",
        length: "2h32m",
        rating: 8.7,
    },
    {
        id: 10,
        title: "The Matrix",
        poster: "matrix",
        banner: "matrixbanner",
        bannerHeight: "400px",
        director: "Lilly Wachowski, Lana Wachowski",
        description: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
        releaseYear: 1999,
        maturity: "R",
        genre: "Sci-Fi",
        length: "2h16m",
        rating: 8.7,
    },
    {
        id: 11,
        title: "Spider-Man: Across the Spider-Verse",
        poster: "spider",
        banner: "spiderbanner",
        bannerHeight: "475px",
        director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
        description: "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
        releaseYear: 2023,
        maturity: "PG",
        genre: "Action",
        length: "2h20m",
        rating: 8.6,
    },
    {
        id: 12,
        title: "Extraction 2",
        poster: "extraction",
        banner: "extractionbanner",
        bannerHeight: "425px",
        director: "Sam Hargrave",
        description: "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world’s deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
        releaseYear: 2023,
        maturity: "R",
        genre: "Action",
        length: "2h02m",
        rating: 7.5,
    },
    {
        id: 13,
        title: "Asteroid City",
        poster: "asteroid",
        banner: "asteroidbanner",
        bannerHeight: "425px",
        director: "Wes Anderson",
        description: "Set in a fictional American desert town circa 1955, the itinerary of a Junior Stargazer/Space Cadet convention (organized to bring together students and parents from across the country for fellowship and scholarly competition) is spectacularly disrupted by world-changing events.",
        releaseYear: 2023,
        maturity: "PG-13",
        genre: "Comedy",
        length: "1h45m",
        rating: 7.4,
    },
    {
        id: 14,
        title: "The Flash",
        poster: "flash",
        banner: "flashbanner",
        bannerHeight: "485px",
        director: "Andy Muschietti",
        description: "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry’s only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
        releaseYear: 2023,
        maturity: "PG-13",
        genre: "Action",
        length: "2h24m",
        rating: 7.3,
    },
    {
        id: 15,
        title: "No Hard Feelings",
        poster: "feelings",
        banner: "feelingsbanner",
        bannerHeight: "450px",
        director: "Gene Stupnitsky",
        description: "On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to “date” their introverted 19-year-old son, Percy, before he leaves for college. To her surprise, Maddie soon discovers the awkward Percy is no sure thing.",
        releaseYear: 2023,
        maturity: "R",
        genre: "Comedy",
        length: "1h43m",
        rating: 6.9,
    },
    {
        id: 16,
        title: "Indiana Jones and the Dial of Destiny",
        poster: "indiana",
        banner: "indianabanner",
        bannerHeight: "450px",
        director: "James Mangold",
        description: "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn’t fall into the wrong hands.",
        releaseYear: 2023,
        maturity: "PG-13",
        genre: "Action",
        length: "2h34m",
        rating: 6.8,
    },
  
    
]