export const data = [
    {
        "id": 1,
        "title": "The Shawshank Redemption",
        "poster": "shawshank",
        "genre": "Drama",
        "length": "2h22m",
        "rating": 9.3,
    },
    {
        "id": 2,
        "title": "The Godfather",
        "poster": "god",
        "genre": "Drama",
        "length": "2h55m",
        "rating": 9.2,
    },
    {
        "id": 3,
        "title": "The Godfather Part II",
        "poster": "god2",
        "genre": "Drama",
        "length": "3h22m",
        "rating": 9.0,
    },
    {
        "id": 4,
        "title": "Schindler's List",
        "poster": "list",
        "genre": "History",
        "length": "3h15m",
        "rating": 8.9,
    },
    {
        "id": 5,
        "title": "Pulp Fiction",
        "poster": "pulp",
        "genre": "Drama",
        "length": "2h34m",
        "rating": 8.9,
    },
    {
        "id": 6,
        "title": "Forrest Gump",
        "poster": "forrest",
        "genre": "Drama",
        "length": "2h22m",
        "rating": 8.8,
    },
    {
        "id": 7,
        "title": "Fight Club",
        "poster": "fight",
        "genre": "Drama",
        "length": "2h19m",
        "rating": 8.8,
    },
    {
        "id": 8,
        "title": "Inception",
        "poster": "inception",
        "genre": "Sci-Fi",
        "length": "2h28m",
        "rating": 8.8,
    },
    {
        "id": 9,
        "title": "The Dark Knight",
        "poster": "darkknight",
        "genre": "Action",
        "length": "2h32m",
        "rating": 8.7,
    },
    {
        "id": 10,
        "title": "The Matrix",
        "poster": "matrix",
        "genre": "Sci-Fi",
        "length": "2h16m",
        "rating": 8.7,
    },
    {
        "id": 11,
        "title": "Spider-Man: Across the Spider-Verse",
        "poster": "spider",
        "genre": "Action",
        "length": "2h20m",
        "rating": 8.6,
    },
    {
        "id": 12,
        "title": "Extraction 2",
        "poster": "extraction",
        "genre": "Action",
        "length": "2h02m",
        "rating": 7.5,
    },
    {
        "id": 13,
        "title": "Asteroid City",
        "poster": "asteroid",
        "genre": "Comedy",
        "length": "1h45m",
        "rating": 7.4,
    },
    {
        "id": 14,
        "title": "The Flash",
        "poster": "flash",
        "genre": "Action",
        "length": "2h24m",
        "rating": 7.3,
    },
    {
        "id": 15,
        "title": "No Hard Feelings",
        "poster": "feelings",
        "genre": "Comedy",
        "length": "1h43m",
        "rating": 6.9,
    },
    {
        "id": 16,
        "title": "Indiana Jones and the Dial of Destiny",
        "poster": "indiana",
        "genre": "Action",
        "length": "2h34m",
        "rating": 6.8,
    }
    
]