export const showdata = [
    {
        id: 1,
        title: "Breaking Bad",
        poster: "breaking",
        banner: "breakingbanner",
        bannerHeight: "500px",
        description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
        releaseYear: "2008-2013",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "62",
        rating: 9.4,
    },
    {
        id: 2,
        title: "Chernobyl",
        poster: "chernobyl",
        banner: "chernobylbanner",
        bannerHeight: "400px",
        description: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
        releaseYear: "2019",
        maturity: "TV-MA",
        genre: "History",
        episodes: "5",
        rating: 9.3,
    },
    {
        id: 3,
        title: "The Sopranos",
        poster: "sopranos",
        banner: "sopranosbanner",
        bannerHeight: "450px",
        description: "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
        releaseYear: "1999-2007",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "86",
        rating: 9.2,
    },
    {
        id: 4,
        title: "The Wire",
        poster: "wire",
        banner: "wirebanner",
        bannerHeight: "400px",
        description: "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
        releaseYear: "2002-2008",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "60",
        rating: 9.2,
    },
    {
        id: 5,
        title: "Band of Brothers",
        poster: "bob",
        banner: "bobbanner",
        bannerHeight: "400px",
        description: "The story of Easy Company of the U.S. Army 101st Airborne Division and their mission in World War II Europe, from Operation Overlord to V-J Day.",
        releaseYear: "2001",
        maturity: "TV-MA",
        genre: "History",
        episodes: "10",
        rating: 9.2,
    },
    {
        id: 6,
        title: "Game of Thrones",
        poster: "got",
        banner: "gotbanner",
        bannerHeight: "400px",
        description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.",
        releaseYear: "2011-2019",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "73",
        rating: 9.0,
    },
    {
        id: 7,
        title: "Mr. Robot",
        poster: "robot",
        banner: "robotbanner",
        bannerHeight: "400px",
        description: "Elliot, a brilliant but highly unstable young cyber-security engineer and vigilante hacker, becomes a key figure in a complex game of global dominance when he and his shadowy allies try to take down the corrupt corporation he works for.",
        releaseYear: "2015-2019",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "45",
        rating: 9.0,
    },
    {
        id: 8,
        title: "True Detective",
        poster: "detective",
        banner: "detectivebanner",
        bannerHeight: "400px",
        description: "Seasonal anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.",
        releaseYear: "2014-Present",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "25",
        rating: 8.9,
    },
    {
        id: 9,
        title: "The Office",
        poster: "office",
        banner: "officebanner",
        bannerHeight: "470px",
        description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
        releaseYear: "2005-2013",
        maturity: "TV-14",
        genre: "Comedy",
        episodes: "188",
        rating: 8.8,
    },
    {
        id: 10,
        title: "Better Call Saul",
        poster: "bcs",
        banner: "bcsbanner",
        bannerHeight: "400px",
        description: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.",
        releaseYear: "2015-2022",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "63",
        rating: 8.8,
    },
    {
        id: 11,
        title: "Silo",
        poster: "silo",
        banner: "silobanner",
        bannerHeight: "400px",
        description: "Men and women live in a giant silo underground with several regulations which they believe are in place to protect them from the toxic and ruined world on the surface.",
        releaseYear: "2023-Present",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "10",
        rating: 8.2,
    },
    {
        id: 12,
        title: "Succession",
        poster: "succession",
        banner: "successionbanner",
        bannerHeight: "400px",
        description: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.",
        releaseYear: "2018-2023",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "39",
        rating: 8.8,
    },
    {
        id: 13,
        title: "The Bear",
        poster: "bear",
        banner: "bearbanner",
        bannerHeight: "400px",
        description: "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.",
        releaseYear: "2022-Present",
        maturity: "TV-MA",
        genre: "Drama",
        episodes: "18",
        rating: 8.4,
    },
    {
        id: 14,
        title: "Black Mirror",
        poster: "mirror",
        banner: "mirrorbanner",
        bannerHeight: "400px",
        description: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
        releaseYear: "2011-Present",
        maturity: "TV-MA",
        genre: "Sci-Fi",
        episodes: "27",
        rating: 8.8,
    },
    {
        id: 15,
        title: "The Flash",
        poster: "flashtv",
        banner: "flashtvbanner",
        bannerHeight: "400px",
        description: "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, and fighting crime in Central City.",
        releaseYear: "2014-2023",
        maturity: "TV-PG",
        genre: "Sci-Fi",
        episodes: "184",
        rating: 7.5,
    },
    {
        id: 16,
        title: "Supernatural",
        poster: "supernatural",
        banner: "supernaturalbanner",
        bannerHeight: "450px",
        description: "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.",
        releaseYear: "2005-2020",
        maturity: "TV-14",
        genre: "Fantasy",
        episodes: "327",
        rating: 8.4,
    },
    

    
]